title: Nguyen Thanh Du (Heidy)
logo: Image/Avata.jpg
description: Data Analyst - Conquering Challenges - Data Enthusiast - Striving for Success
theme: jekyll-theme-hacker
github:
  is_project_page: false  
sass:
  style: compressed   
footer.site-footer { display: none !important; }
