title: Nguyen Thanh Du (Heidy)
logo: Image/Avata.jpg
description: |
  <br> Data Analyst <br>  | 
  Conquering Challenges - Data Enthusiast  
  - Striving for Success  
  <br>
  <a href="https://www.linkedin.com/in/nguyenthanhdu/" target="_blank" title="LinkedIn">
    <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="LinkedIn" width="32" style="border-radius: 50%; background: #0a66c2;"/>
  </a>
theme: jekyll-theme-minimal
github:
  is_project_page: false  
sass:
  style: compressed   
footer.site-footer { display: none !important; }
