title: Nguyen Thanh Du (Heidy)
logo: Image/Avata.jpg
description: 
 "<b>Data Analyst</b><br>Conquering Challenges - Data Enthusiast - Striving for Success"
theme: jekyll-theme-minimal
github:
  is_project_page: false  
sass:
  style: compressed   
footer.site-footer { display: none !important; }
